* https://towardsdatascience.com/linear-algebra-cheat-sheet-for-deep-learning-cd67aba4526c

In [2]:
import numpy as np

In [55]:
print("Hello World")

Hello World


In [56]:
dummy = np.array([[1],[2],[3]])
print(dummy)
dummy.shape

[[1]
 [2]
 [3]]


(3, 1)

In [58]:
x = [1,2,3]
y = [1,2,3]
product = []

for i in range(len(x)):
    product.append(x[i]*y[i])
print(product)

[1, 4, 9]


In [59]:
x = np.array([1,2,3])
y = np.array([1,2,3])

prod = x*y
print(prod)

[1 4 9]


* Neural networks store weights in matrices
* GPU used to compute matrices 

In [60]:
x, y
x.shape, y.shape

((3,), (3,))

In [61]:
x + y

array([2, 4, 6])

In [62]:
x - y

array([0, 0, 0])

In [63]:
y / x

array([1., 1., 1.])

In [64]:
y = np.array([1,2,3])
x = np.array([2,3,4])

In [65]:
np.dot(y,x)

20

In [66]:
np.dot(x,y)

20

Hadamard product

In [67]:
a = np.array([1,2,3])
b = np.array([[1],[2],[3]])

a*b

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [68]:
y * x

array([ 2,  6, 12])

Vector field..whats this!!?

It shows how far a point will move if a vector function like addition or mult is applied to the point

Very import for visualizing Gradient Descent

## Start from Matrices

In [69]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
a.shape

(2, 3)

In [72]:
b = np.array([
 [1,2,3]
])
print(b.shape)
b.shape == (1,3)

(1, 3)


True

In [73]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
a+1

array([[2, 3, 4],
       [5, 6, 7]])

In [75]:
a = np.array([
 [1,2],
 [3,4]
])
b = np.array([
 [1,2],
 [3,4]
])


In [76]:
a+b

array([[2, 4],
       [6, 8]])

In [77]:
a-b

array([[0, 0],
       [0, 0]])

In [78]:
a/b

array([[1., 1.],
       [1., 1.]])

Numpy broadcasting

In [6]:
a = np.array([[2,3],
            [1,1]])

b = np.array([[1,1],
            [2,3]])

a*b # hadamard product

array([[2, 3],
       [2, 3]])

In [7]:
a = np.array([[1,2],
             [3,4]])

a.T

array([[1, 3],
       [2, 4]])

In [10]:
a = np.array([1,2,3])

b = np.array([[1],[2],[3]])
b

array([[1],
       [2],
       [3]])

In [12]:
x = np.dot(a,b) ; x

array([14])

In [13]:
x.shape

(1,)