Eager API: Operations are executed as they are called from
Python. An easy version of tf

What is graph in tf? I dont know yet...

In [1]:
from __future__ import absolute_import, division, print_function

import numpy as np
import tensorflow as tf

In [2]:
tf.enable_eager_execution()
tfe = tf.contrib.eager
print("Done")

Done


In [8]:
# some tensors

a = tf.constant(4)
b = tf.constant(4)
a

<tf.Tensor: id=18, shape=(), dtype=int32, numpy=4>

In [9]:
c = a + b
print(c)

tf.Tensor(8, shape=(), dtype=int32)


In [10]:
d = a * b
print(d)

tf.Tensor(16, shape=(), dtype=int32)


In [13]:
# tensors and numpy

a = tf.constant([[2., 1.],[1., 0.]], dtype=tf.float32)

b = np.array([[3., 0.], [5., 1.]], dtype=np.float32)

print("Tensor: \n a = %s" %(a))
print("\n")
print("Tensor: \n b = %s" %(b))

Tensor: 
 a = tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)


Tensor: 
 b = [[3. 0.]
 [5. 1.]]


In [14]:
c = a + b
print(c)

tf.Tensor(
[[5. 1.]
 [6. 1.]], shape=(2, 2), dtype=float32)


In [15]:
d = tf.matmul(a,b)
print(d)

tf.Tensor(
[[11.  1.]
 [ 3.  0.]], shape=(2, 2), dtype=float32)


In [21]:
# tensor and numpy array shape
d.shape, b.shape

(TensorShape([Dimension(2), Dimension(2)]), (2, 2))

In [23]:
a

<tf.Tensor: id=26, shape=(2, 2), dtype=float32, numpy=
array([[2., 1.],
       [1., 0.]], dtype=float32)>

In [22]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j])

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
